# Generated by Django 4.2.6 on 2023-10-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('received', models.TextField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('received', 'Received'), ('unknown', 'Unknown')], max_length=30)),
                ('size', models.CharField(choices=[('1', 'XS'), ('2', 'S'), ('3', 'M'), ('4', 'L'), ('5', 'XL')], max_length=10)),
                ('to_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelLocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('free', 'Free'), ('full', 'Full'), ('unknown', 'Unknown')], max_length=30)),
                ('size', models.CharField(choices=[('1', 'XS'), ('2', 'S'), ('3', 'M'), ('4', 'L'), ('5', 'XL')], max_length=10)),
                ('to_delete', models.BooleanField(default=False)),
                ('parcel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lockers', to='db.parcel', unique=True)),
            ],
        ),
    ]
