# Generated by Django 4.2.6 on 2023-10-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_received_parcel_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='to_delete',
        ),
        migrations.RemoveField(
            model_name='parcellocker',
            name='to_delete',
        ),
    ]
